### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jamesboone** [DestinyVaultHelper/dvh#2]
First of all, great job!
It would be very helpful for characters with three of the same character types to have a way to know which one is which. Destiny app shows the characters' banner but you might be able to also get the species type. I have three lvl 40 warlocks, one awoken male and female, and one male human. All other factors can possibly change, but those cannot.

**Comment by dswistowski** [comment]
Nice idea, i will try to modify toolbar a bit, to fit there that information. I do not want to copy look from destiny app, because i want have tab's as small as it's possible to focus user on items

**Comment by jamesboone** [comment]
Yup makes sense, also I noticed you do have the banners in the app so that
does help but it would still be nice to show something that is permanent to
the character.

**Comment by dswistowski** [comment]
After few test i have best version:
![device-2015-11-02-213134](https://cloud.githubusercontent.com/assets/197861/10893472/2e6f1b3a-81a9-11e5-8ab7-1159e41db4af.png)

but i want to think if put it to official version. I'm starting about creating setings page and add it as opt in

**Comment by jamesboone** [comment]
Nice! Definitely more functional than any other app out there trying to do
this. Thanks for the quick changes... I wasn't expecting anything.

**Comment by dswistowski** [comment]
Its pushed in 1.6.2 version
